"""Ubuntu packaging: checksums, requirements export, and rsync transfer plan."""
from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path
from typing import List

from . import console
from .util import sha256_file


def checksums(root: Path, which: str = "clean") -> Path:
    target = root / "data" / which
    entries = []
    for p in sorted(target.rglob("*")):
        if p.is_file():
            entries.append({"path": str(p.relative_to(root)), "sha256": sha256_file(p)})
    out = root / "metadata" / f"{which}_audio.sha256"
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = [f"{e['sha256']}  {e['path']}" for e in entries]
    out.write_text("\n".join(lines) + "\n")
    console.ok(f"{len(entries)} checksums -> {out.relative_to(root)}")
    return out


def export_requirements(root: Path, python: str = ".venv/bin/python") -> Path:
    out = root / "requirements-mac.txt"
    res = subprocess.run(
        ["uv", "pip", "freeze", "--python", str(root / python)],
        capture_output=True, text=True, cwd=root,
    )
    if res.returncode != 0:
        console.error(f"uv pip freeze failed: {res.stderr.strip()[:400]}")
    else:
        out.write_text(res.stdout)
        console.ok(f"Requirements -> {out.name}")
    return out


def rsync_plan(root: Path, host: str, name: str = "musicgen-style") -> Path:
    remote_base = f"{host}:~/ai/projects/{name}/"
    script = f"""#!/usr/bin/env bash
set -euo pipefail
# Generated by musictrain package --host {host}

REMOTE="{remote_base}"

echo ">> Creating remote directory tree"
ssh {host.split(':')[0]} "mkdir -p ~/ai/projects/{name}/{{data/raw,data/clean,data/train,data/val,data/test,metadata,configs,checkpoints,outputs,logs,scripts}}"

echo ">> Syncing code + metadata (excluding heavy/local data)"
rsync -avP \\
  --exclude='.venv' \\
  --exclude='.git' \\
  --exclude='data/raw' \\
  --exclude='data/clean' \\
  --exclude='data/segments' \\
  --exclude='data/train' \\
  --exclude='data/val' \\
  --exclude='data/test' \\
  --exclude='checkpoints' \\
  --exclude='outputs/*.wav' \\
  --exclude='logs' \\
  {root}/ "$REMOTE"

echo ">> Syncing normalized audio separately"
rsync -avP {root}/data/clean/ "$REMOTE"data/clean/

echo ">> Verifying checksums on remote"
ssh {host.split(':')[0]} "cd ~/ai/projects/{name} && shasum -a 256 -c metadata/clean_audio.sha256"
"""
    out = root / "scripts" / "rsync_to_ubuntu.sh"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(script)
    out.chmod(0o755)
    console.ok(f"Transfer plan -> {out.relative_to(root)}")
    return out


def package(
    root: Path,
    host: str = "",
    which: str = "clean",
    python: str = ".venv/bin/python",
    tarball: bool = False,
) -> dict:
    console.step("Packaging for Ubuntu")
    summary: dict = {}

    summary["checksums"] = str(checksums(root, which).relative_to(root))
    summary["requirements"] = str(export_requirements(root, python).relative_to(root))
    if host:
        summary["rsync_plan"] = str(rsync_plan(root, host).relative_to(root))
    else:
        console.info("No --host given; skipping rsync plan (add --host user@ubuntu).")

    if tarball:
        out = root / "metadata" / "musicgen-style-mac.tar.gz"
        subprocess.run(
            [
                "tar", "-czf", str(out),
                "--exclude=.venv", "--exclude=.git", "--exclude=data/raw",
                "--exclude=data/clean", "--exclude=checkpoints", "--exclude=outputs",
                "-C", str(root.parent), root.name,
            ],
            check=False,
        )
        summary["tarball"] = str(out.relative_to(root))
        console.ok(f"Tarball -> {out.relative_to(root)}")

    (root / "metadata" / "package_summary.json").write_text(
        json.dumps(summary, indent=2)
    )
    console.ok("Packaging complete.")
    return summary
