"""Synthetic lyric corpus expander (deterministic, offline).

The fine-tune's quality scales with corpus size, but real lyrics are the
bottleneck. This module expands the dataset with *deterministic* structured
bars generated by the offline engine (``lyrics._generate_offline``): one song
per (artist × mood × topic × seed) combo, written straight into
``lyrics/<aid>/songs.jsonl`` via the merge helper — existing songs are kept.

Because generation is fully offline and seeded, re-running with the same
arguments is a no-op (titles are stable), so it is safe to call repeatedly
after adding new moods/topics.
"""
from __future__ import annotations

import random
from pathlib import Path
from typing import Dict, List, Optional

from . import console
from .artists import ARTISTS
from .lyrics import BeatContext, _generate_offline
from .lyricdataset import append_records

KEYS = ["A minor", "C major", "D minor", "G major", "E minor", "F major",
        "B minor", "G minor", "A major", "F minor", "C minor", "E major"]

DEFAULT_MOODS = ["dark", "emotional", "braggadocious", "melancholic", "aggressive",
                 "confident", "reflective", "menacing", "smooth", "heartbroken",
                 "determined", "gritty"]

DEFAULT_TOPICS = ["struggle", "pain", "money", "success", "loyalty", "love",
                  "heartbreak", "street", "hustle", "family", "loss", "demons",
                  "party", "fame", "confidence", "grind", "respect", "come-up",
                  "boss", "freedom"]

_STRUCTURE_ROLES = ["intro", "verse", "hook", "verse", "hook", "outro"]


def _structure() -> list:
    """A compact full-song structure (intro/verse/hook x2/outro)."""
    from .lyrics import SectionSpec

    return [SectionSpec(role=r, bars=4 if r == "intro" else (8 if r in ("hook", "outro") else 16))
            for r in _STRUCTURE_ROLES]


def generate_corpus(
    root: Path,
    artists: Optional[List[str]] = None,
    per_artist: int = 25,
    moods: Optional[List[str]] = None,
    topics: Optional[List[str]] = None,
    seed: int = 7,
    limit: int = 0,
    dry_run: bool = False,
) -> Dict[str, int]:
    """Generate deterministic synthetic songs and merge them into lyrics/.

    Returns {"added": n}. ``dry_run`` plans the corpus and reports the size
    without writing anything.
    """
    want = [a.strip().lower() for a in (artists or []) if a and a.strip()]
    profiles = [p for p in ARTISTS if not want or p.id in want or p.name.lower() in want]
    moods = moods or DEFAULT_MOODS
    topics = topics or DEFAULT_TOPICS
    rng = random.Random(seed)

    records: List[dict] = []
    console.step(f"Synthesizing corpus: {len(profiles)} artist(s) x {per_artist} song(s) (seed={seed})")
    for prof in profiles:
        made = 0
        for i in range(per_artist):
            if limit and len(records) >= limit:
                break
            mood = moods[i % len(moods)]
            topic = topics[(i * 7 + seed) % len(topics)]
            lo, hi = prof.bpm_range
            bpm = float(rng.randint(lo, hi))
            key = KEYS[(i + seed) % len(KEYS)]
            ctx = BeatContext(
                bpm=bpm, key=key, swing="straight", energy=0.5,
                artist=prof.id, mood=mood, topic=topic,
                structure=_structure(), seed=seed + i,
            )
            res = _generate_offline(ctx, prof)
            lines = [ln for s in res.sections for ln in s["lines"]]
            if len(lines) < 8:
                continue
            records.append({
                "artist": prof.name,
                "title": f"[synth {i + 1:03d}] {mood} {topic}",
                "lines": lines,
                "mood": mood, "topic": topic,
                "source": f"synthetic-seed{seed}",
            })
            made += 1
        console.info(f"  {prof.name}: {made} synthetic song(s)")
        if limit and len(records) >= limit:
            break

    if dry_run:
        console.ok(f"Dry run: would add {len(records)} synthetic song(s) across {len(profiles)} artist(s)")
        return {"added": len(records)}

    if not records:
        console.warn("Nothing to add (check moods/topics/limit).")
        return {"added": 0}
    summary = append_records(root, records)
    return {"added": summary["added"]}
